version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/HostedApp/ClientApp"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/src/HostedApp"
    schedule:
      interval: "daily"

  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"